name: mkwpp-api-prod

volumes:
  staticfiles:

services:
  cache:
    image: redis:7.4.2
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn mkwpp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    volumes:
      - staticfiles:/home/app/web/staticfiles
    expose:
      - 8000:8000
    depends_on:
      - cache

  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - app
