volumes:
  postgres:
  smtp4dev:

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:7.4.2
    ports:
      - 6379:6379

  smtp:
    image: rnwood/smtp4dev:latest
    volumes:
      - smtp4dev:/smtp4dev
    ports:
      - 5000:80
      - 25:25
      - 143:143
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - cache
      - smtp
