# Generated by Django 5.1.1 on 2025-02-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost'),
        ('timetrials', '0019_reverse_user_player_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player',
            field=models.OneToOneField(blank=True, help_text='Player profile associated with this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetrials.player'),
        ),
    ]
