# Generated by Django 5.1.1 on 2025-02-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reverse_user_player_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('salt', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
