# Generated by Django 5.1.1 on 2024-09-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nonsc', 'Non-Shortcut'), ('sc', 'Shortcut'), ('unres', 'Unrestricted')])),
                ('is_lap', models.BooleanField(blank=True, help_text='OFF for course, ON for lap, and null for both', null=True)),
                ('score_count', models.IntegerField(help_text='Number of scores qualifying for the category')),
                ('total_score', models.IntegerField(help_text='Sum of all lowest scores')),
                ('total_rank', models.IntegerField(help_text='Sum of the rank of all lowest scores')),
                ('player_name', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='timetrials.player')),
                ('player_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerstats', to='timetrials.region')),
            ],
        ),
    ]
