# Generated by Django 5.1.1 on 2024-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0002_playerstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': 'player stats', 'verbose_name_plural': 'player stats'},
        ),
        migrations.AddField(
            model_name='playerstats',
            name='total_standard',
            field=models.IntegerField(default=0, help_text='Sum of the standard of all lowest scores'),
            preserve_default=False,
        ),
    ]
