# Generated by Django 5.1.1 on 2024-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0003_playerstats_total_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='total_record_ratio',
            field=models.FloatField(default=0, help_text='Sum of lowest score to record ratios'),
            preserve_default=False,
        ),
    ]
