# Generated by Django 5.1.1 on 2024-09-14 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0004_playerstats_total_record_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player_region',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playerstats', to='timetrials.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='is_ranked',
            field=models.BooleanField(default=False, help_text='Whether this region has a dedicated tops chart and player rankings.'),
        ),
        migrations.AlterField(
            model_name='region',
            name='type',
            field=models.CharField(choices=[('world', 'World'), ('continent', 'Continent'), ('country_group', 'Country Group'), ('country', 'Country'), ('subnational_group', 'Subnational Group'), ('subnational', 'Subnational')], max_length=32),
        ),
    ]
