# Generated by Django 5.1.1 on 2024-10-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0008_convert_category_to_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_score_count', models.IntegerField(help_text='Number of top region score per track')),
                ('category', models.IntegerField(choices=[(0, 'Non-Shortcut'), (1, 'Shortcut'), (2, 'Unrestricted')], default=0)),
                ('is_lap', models.BooleanField(blank=True, help_text='OFF for course, ON for lap, and null for both', null=True)),
                ('participation_count', models.IntegerField(help_text='Number of track-lap combination with enough scores to qualify')),
                ('score_count', models.IntegerField(help_text='Number of scores qualifying for the category')),
                ('total_score', models.IntegerField(help_text='Sum of all lowest scores')),
                ('total_rank', models.IntegerField(help_text='Sum of the rank of all lowest scores')),
                ('total_standard', models.IntegerField(help_text='Sum of the standard of all lowest scores')),
                ('total_record_ratio', models.FloatField(help_text='Sum of lowest score to record ratios')),
                ('total_records', models.IntegerField(help_text='Sum of track records')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='timetrials.region')),
            ],
            options={
                'verbose_name': 'region stats',
                'verbose_name_plural': 'region stats',
            },
        ),
    ]
