# Generated by Django 5.1.1 on 2024-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0009_regionstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='total_records',
            field=models.IntegerField(help_text='Number of records'),
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='top_score_count',
            field=models.IntegerField(choices=[(0, 'Every regional score (minimum of 3 to count)'), (1, 'Regional record only'), (3, 'Top 3 regional scores'), (5, 'Top 5 regional scores'), (10, 'Top 10 regional scores')], default=0, help_text='Number of top region score per track'),
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='total_rank',
            field=models.BigIntegerField(help_text='Sum of the rank of all lowest scores'),
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='total_records',
            field=models.IntegerField(help_text='Number of records'),
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='total_score',
            field=models.BigIntegerField(help_text='Sum of all lowest scores'),
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='total_standard',
            field=models.BigIntegerField(help_text='Sum of the standard of all lowest scores'),
        ),
    ]
