# Generated by Django 5.1.1 on 2024-11-01 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0010_alter_regionstats_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionstats',
            name='top_score_count',
            field=models.IntegerField(choices=[(0, 'Every regional score (minimum of 3 to count)'), (1, 'Regional record only'), (3, 'Top 3 regional scores'), (5, 'Top 5 regional scores'), (10, 'Top 10 regional scores')], default=1, help_text='Number of top region score per track'),
        ),
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('description', models.CharField(max_length=1024)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='timetrials.player')),
            ],
        ),
    ]
