# Generated by Django 5.1.1 on 2024-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0012_sitechampion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcup',
            name='code',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionstats',
            name='top_score_count',
            field=models.IntegerField(choices=[(0, 'Every regional score'), (1, 'Regional record only'), (3, 'Top 3 regional scores'), (5, 'Top 5 regional scores'), (10, 'Top 10 regional scores')], default=1, help_text='Number of top region score per track'),
        ),
    ]
