# Generated by Django 5.1.1 on 2024-11-29 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0013_trackcup_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='score',
            name='status',
        ),
        migrations.RemoveField(
            model_name='score',
            name='time_reviewed',
        ),
        migrations.RemoveField(
            model_name='score',
            name='time_submitted',
        ),
        migrations.AddField(
            model_name='score',
            name='admin_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='initial_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='timetrials.player'),
        ),
        migrations.AlterField(
            model_name='score',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='timetrials.track'),
        ),
        migrations.CreateModel(
            name='EditScoreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'On hold')], default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitter_note', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link_edited', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('ghost_link_edited', models.BooleanField(default=False)),
                ('ghost_link', models.URLField(blank=True, max_length=255, null=True)),
                ('comment_edited', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_submissions', to='timetrials.score')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edit submission',
                'verbose_name_plural': 'edit submissions',
            },
        ),
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Finish time in milliseconds (e.g. 69999 for 1:09.999).')),
                ('category', models.IntegerField(choices=[(0, 'Non-Shortcut'), (1, 'Shortcut'), (2, 'Unrestricted')], default=0)),
                ('is_lap', models.BooleanField(default=False, help_text='Off for 3lap, on for flap.')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date set')),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('ghost_link', models.URLField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'On hold')], default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitter_note', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='timetrials.player')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='timetrials.track')),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
        ),
    ]
