# Generated by Django 5.1.1 on 2024-11-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0014_score_submissions_rework'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresubmission',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='timetrials.score'),
        ),
    ]
