# Generated by Django 5.1.1 on 2025-01-04 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0015_score_submission_related_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSubmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(help_text='The player the submitter is granted permission to create submissions for.', on_delete=django.db.models.deletion.CASCADE, related_name='submitters', to='timetrials.player')),
                ('submitter', models.ForeignKey(help_text='The user being granted permission to create submissions for the player.', on_delete=django.db.models.deletion.CASCADE, related_name='submittees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player submitter',
                'verbose_name_plural': 'player submitters',
                'constraints': [models.UniqueConstraint(fields=('player', 'submitter'), name='unique_player_submitter')],
            },
        ),
    ]
