# Generated by Django 5.1.1 on 2025-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0016_playersubmitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardlevel',
            name='code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
