# Generated by Django 5.1.1 on 2025-02-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0018_scores_fix_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
