# Generated by Django 5.1.7 on 2025-04-12 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetrials', '0019_reverse_user_player_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='timetrials.region'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='timetrials.playerstatsgroup'),
            preserve_default=False,
        ),
    ]
